### ISSUE TITLE
Consider renaming the project to o2g

### ISSUE THREAD

**Issue by mehdisadeghi** [hiposfer/o2g#112]
@carocad I am thinking about renaming the whole project to _o2g_. It is shorter and easier to use. Initially I wanted to move o2g cli and web into their own repositories, but after some more thought (!) I think it is better to leave them inside this repo, because there is not much to put aside in a separate repository.

After renaming, one would be able to install it like this:

    $ pip install o2g

And in scripts one would be able to use it like this:

    import o2g

What do you think?

**Comment by carocad** [comment]
After using the project for quite some time it does get a bit complicated to mention osmtogtfs since the name (although logical) is not easy to remember nor write.

I support your decision of changing it :)

**Comment by mehdisadeghi** [comment]
Done in #115
