### ISSUE TITLE
consider adding a feed_info file to o2g feed dump

### ISSUE THREAD

**Issue by carocad** [hiposfer/o2g#122]
See GTFS spec: https://developers.google.com/transit/gtfs/reference/#feed_infotxt

I think that the `feed_publisher_name` and `feed_version` should be specially interesting for us since they directly involve information related both to o2g and to hiposfer

**Comment by mehdisadeghi** [comment]
@carocad that totally makes sense. What should go inside `feed_version` in your opinion?

**Comment by mehdisadeghi** [comment]
I think epoch approach is better and simpler, since for a counter we would need to keep track of it in order to increase it every time.
