### ISSUE TITLE
trouble with the --zipfile arguments

### ISSUE THREAD

**Issue by nlehuby** [hiposfer/o2g#132]
I don't understand how the `zipfile` argument should be used:

`o2g --outdir phebus  ~/path/to/phebus.osm.pbf --dummy --zipfile` errors with the following
```
TypeError: join() argument must be str or bytes, not 'bool'
```

whereas `o2g --outdir phebus  ~/path/to/phebus.osm.pbf --dummy --zipfile phebus.zip` outputs
```
usage: o2g [-h] [--outdir OUTDIR] [--zipfile] [--dummy] [--loglevel LOGLEVEL]
           [--version]
           OSMFILE
o2g: error: unrecognized arguments: phebus.zip

```

**Comment by mehdisadeghi** [comment]
You are using the `zipfile` option correctly. This appears to be a bug (it works for me). What is the output of `o2g --version`. Did you install it with pip3?

**Comment by nlehuby** [comment]
o2g 0.5.1

**Comment by mehdisadeghi** [comment]
@nlehuby please ignore my last comment. `zipfile` needs an argument, if you provide it the output will be zipped under that name, otherwise will be saved to the `outdir` as text files. The master branch doesn't have that problem, I'm publishing a new version though.

**Comment by nlehuby** [comment]
thanks :+1:
